name: flutter_firebase_ai_sample
description: "Flutter application demonstrates Firebase AI Logic capabilities through a series of interactive demos."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^6.1.1
  flutter_riverpod: ^2.6.1
  flutter_soloud: ^3.1.6
  firebase_core: ^4.0.0
  camera: ^0.11.1
  flutter_image_compress: ^2.4.0
  waveform_flutter: ^1.2.0
  flutter_animate: ^4.5.2
  firebase_ai: ^3.1.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  flutter_markdown: ^0.7.7+1
  file_picker: ^10.2.1
  thumbnailer: ^3.1.0
  cross_file: ^0.3.4+2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gemini-logo.png
    - assets/firebase-ai-logic.png
